version: '3'
services:
  db:
    image: "postgres:12"
    container_name: "rating_postgres"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust